type = "list"
title = "Awards"

[[items]]
date = "2026"
content = "**First Prize, 2024 Outstanding Paper Award, Automation of Electric Power Systems**<br/><em>Editorial Office of Automation of Electric Power Systems</em>"

[[items]]
date = "2025"
content = "**Eric and Wendy Schmidt AI in Science Postdoctoral Fellowship**<br/><em>Cornell University and Schmidt Sciences, LLC</em>"

[[items]]
date = "2025"
content = "**Finalist of the IEEE Power & Energy Society Ph.D. Dissertation Challenge** (**Top 20**)<br/><em>IEEE Power & Energy Society at 2025 IEEE PES Grid Edge Technologies Conference</em>"

[[items]]
date = "2024"
content = "**Ezra Systems Scholar**<br/><em>Cornell University Systems Engineering Program</em>"

[[items]]
date = "2024"
content = "**Tsinghua Cercis Scholar** (<span class=\"md-orange\"><strong>10 recipients university-wide</strong></span>)<br/><em>Tsinghua University</em>"

[[items]]
date = "2024"
content = "**Tsinghua Outstanding Ph.D. Dissertation Award** <br/><em>Tsinghua University</em>"

[[items]]
date = "2024"
content = "**Beijing Outstanding Ph.D. Graduate Award** <br/><em>Beijing Municipal Education Commission</em>"

[[items]]
date = "2024"
content = "**Tsinghua Outstanding Ph.D. Graduate Award** <br/><em>Tsinghua University</em>"

[[items]]
date = "2023"
content = "**Tsinghua Jiang Nanxiang Principal Scholarship** (<span class=\"md-orange\"><strong>20 recipients university-wide</strong></span>)<br/><em>Tsinghua University</em>"

[[items]]
date = "2023"
content = "**Doctoral National Scholarship** (<span class=\"md-orange\"><strong>Top 1% nation-wide</strong></span>)<br/><em>Ministry of Education of China</em>"

[[items]]
date = "2022"
content = "<span class=\"md-orange\"><strong>Kirin Cup </strong></span>**in Electronic Circuit Design Elite Challenge** (<span class=\"md-orange\"><strong>National championship team</strong></span>)<br/><em>China Electronic Engineering Association</em>"

[[items]]
date = "2022"
content = "<span class=\"md-orange\"><strong>Golden Medal</strong></span> **in International Exhibition of Inventions Geneva** <br/><em>World Intellectual Property Organization</em>"

[[items]]
date = "2022"
content = "**Outstanding Paper Award**<br/><em>China Association for Science and Technology</em>"

[[items]]
date = "2021"
content = "**Frontrunner 5000 Top Articles in Outstanding S&T Journals of China**<br/><em>Institute of Science and Technical Information of China</em>"

[[items]]
date = "2021"
content = "**First Prize, 2020 Outstanding Paper Award, Automation of Electric Power Systems**<br/><em>Editorial Office of Automation of Electric Power Systems</em>"

[[items]]
date = "2019"
content = "**Beijing Outstanding Undergraduate Thesis Award** (<span class=\"md-orange\"><strong>Sole recipient in the EE department</strong></span>)<br/><em>Beijing Municipal Education Commission</em>"

[[items]]
date = "2019"
content = "**Beijing Excellent Bachelor Award** (**Top 2%**)<br/><em>Beijing Municipal Education Commission</em>"

[[items]]
date = "2019"
content = "**Tsinghua Outstanding Undergraduate Thesis Award**<br/><em>Tsinghua University</em>"

[[items]]
date = "2019"
content = "**Tsinghua Outstanding Undergraduate Graduate Award**<br/><em>Tsinghua University</em>"

[[items]]
date = "2018"
content = "**Tsinghua First-Class Undergraduate Comprehensive Excellence Scholarship** <br/><em>Tsinghua University</em>"

[[items]]
date = "2017"
content = "**Tsinghua Academic Excellence Scholarship**<br/><em>Tsinghua University</em>"

[[items]]
date = "2016"
content = "**Ultra High Voltage Power Grid Scholarship** (**4/134**)<br/><em>State Grid Corporation of China</em>"

[[items]]
date = "2016"
content = "**Tsinghua Academic Excellence Scholarship**<br/><em>Tsinghua University</em>"
