type = "sectioned"
title = "Experiences"

[[sections]]
id = "academic_appointments_heading"
type = "text"
content = "<h3 class=\"text-xl font-serif font-bold text-primary\">Academic Appointments</h3>"

[[sections]]
id = "academic_appointments"
type = "card"

  [[sections.items]]
  title = "Schmidt AI in Science Postdoctoral Associate"
  subtitle = "Cornell University AI for Science Institute, College of Engineering"
  date = "2025/09 - Present"
  content = "**Mentor:** Prof. Fengqi You in PEESE Lab"
  image = "/Cornell.svg"

  [[sections.items]]
  title = "Ezra Postdoctoral Associate"
  subtitle = "College of Engineering, Cornell University"
  date = "2024/09 - 2025/08"
  content = "**Mentor:** Prof. Fengqi You in PEESE Lab"
  image = "/Cornell.svg"

[[sections]]
id = "education_heading"
type = "text"
content = "<h3 class=\"text-xl font-serif font-bold text-primary\">Education</h3>"

[[sections]]
id = "education"
type = "card"

  [[sections.items]]
  title = "Ph.D. in Electrical Engineering"
  subtitle = "Department of Electrical Engineering, Tsinghua University"
  date = "2019/08 - 2024/06"
  content = """**Supervisor:** Prof. Wenchuan Wu<br/>
**Laboratory:** EMS Lab led by Prof. Hongbin Sun<br/>"""
  image = "/Tsinghua.svg"

  [[sections.items]]
  title = "B.E. in Electrical Engineering"
  subtitle = "Department of Electrical Engineering, Tsinghua University"
  date = "2015/08 - 2019/07"
  image = "/Tsinghua.svg"
