[[news]]
date = "2025-09"
content = "I start my **Schmidt AI in Science Postdoctoral Associate** position at Cornell University with the **Eric and Wendy Schmidt AI in Science Postdoctoral Fellowship**."

[[news]]
date = "2024-09"
content = "I start my **Ezra Postdoctoral Associate** position at Cornell University."

[[news]]
date = "2024-07"
content = "Our paper entitled *Stochastic Flexibility Evaluation for Virtual Power Plant by Aggregating Distributed Energy Resources* is selected as an **ESI Top 1% Highly Cited Paper**."

[[news]]
date = "2024-06"
content = "I graduate from Tsinghua University with the honors **Beijing & Tsinghua Outstanding Ph.D. Graduate** and **Tsinghua Outstanding Ph.D. Dissertation**."

[[news]]
date = "2024-05"
content = "I have successfully passed my Ph.D. dissertation defense, entitled *Flexibility Aggregation and Coordination of Diverse Energy Resources*."

[[news]]
date = "2024-05"
content = "I was selected as a **Tsinghua Cercis Scholar**."

[[news]]
date = "2023-12"
content = "I received the **Tsinghua University Jiang Nanxiang Principal Scholarship**."
